<?php

/**
 * set DEFAULT PATHS and RUNNING where ZeeltePHP is running.
 * default - production first - we presume to be in build (production).
 *         - development env  - no .env file.
 */
function zp_loadRunEnvironment() {
     define('PATH_ZP_ENVfile', './zeeltephp/.env'); // exist only in builds, but always required
     if (!is_file('./zeeltephp/.env')) {
          // no .env file - presume project run dev mode
          // default values are generated by vite-plugin/zeeltephp_postbuild()
          zp_loadRunEnvironmentDev();
          return;
     }
     // # default BUILD prod-env (build/api/zeeltephp)
     define('PATH_CPROOT',   getcwd().'/zeeltephp');   // to strip full-path from errors
     define('PATH_ZPLIB',    './zeeltephp/zplib/');    // from CP /src/lib/zplib
     define('PATH_ZPROUTES', './zeeltephp/zproutes/'); // from CP /src/routes/
     define('PATH_ZPLOG',    './zeeltephp/log/');      // php errors

}


/**
 * set DEFAULT PATHS and RUNNING environment in run dev mode and /consumer-project-root/
 */
function zp_loadRunEnvironmentDev() {
     // # exits first
     // * todo really dev-evn? check if might by prod-env when .env file is missing

     //// main()
     $debug = false;

     // # allow CORS for env node 5173 and httpd 80,443 (allow from anywhere *)
     zp_allow_cors();

     // # check environment context 
     //   in which context am I running (self/consumer? 
     //     as lib-package       (cp: consumer project) (default) 
     //     or lib-development   (zp: self svelte-zeeltephp lib-project)
     $path_ZP_cpRoot  = realpath(getcwd().'/../../');      // expected /path/to/htdocs/<your-project>/static/api 
     $path_ZP_APIPHP  = "$path_ZP_cpRoot/node_modules/zeeltephp/api";
     $isLibPackage    = is_dir($path_ZP_APIPHP);
     $isSelf          = basename($path_ZP_cpRoot) == 'svelte-zeeltephp';
     $context = "init";

     if (!$isLibPackage && !$isSelf) {
          // Am I linked as package?
          // # change PHP current working path
          $context = "consumer-linked";
          $path_ZP_APIPHP = "$path_ZP_cpRoot/../svelte-zeeltephp/static/api";
     }
     if ($isLibPackage && !$isSelf) {
          // consumer project :-)
          // nothing todo as this should be default
          $context = "lib-package";
     }
     else if (!$isLibPackage && $isSelf) {
          // its me, my-self
          $context = "self-dev";
          $path_ZP_APIPHP  = "$path_ZP_cpRoot/static/api";
     }
     chdir($path_ZP_APIPHP);
     
     define('PATH_CPROOT',    $path_ZP_cpRoot); // to strip paths from errors
     define('PATH_ZPLIB',    "$path_ZP_cpRoot/src/lib/zplib");    // from CP /src/lib/zplib
     define('PATH_ZPROUTES', "$path_ZP_cpRoot/src/routes"); // from CP /src/routes/
     define('PATH_ZPLOG',    "$path_ZP_cpRoot/.zp-log");    // php errors
     define('PATH_ZPAPIPHP',  $path_ZP_APIPHP);    // php errors

     // # change some PHP settings at runtime
     //    if allowed, lets try anyway, add @ for no output
     // Disable default PHP error display
     @ini_set('display_errors', 0);
     @ini_set('display_startup_errors', 0);
     // re-route default errors -log  
     @ini_set('error_log', $path_ZP_LOG);

      // some debugging output when required
     if (false) {
          echo "<li>$context";
          echo "<li>isSelf         ".($isSelf ? 'true':'false');
          echo "<li>isLibPackage     ".($isLibPackage ? 'true':'false');
          echo "<li>PATH_CPROOT    ".PATH_CPROOT;
          echo "<li>PATH_ZPAPIPHP  ".PATH_ZPAPIPHP;
          echo "<li>PATH_ZPLOG     ".PATH_ZPLOG;
          echo "<li>PATH_ZPLIB     ".PATH_ZPLIB;
          echo "<li>PATH_ZPROUTES  ".PATH_ZPROUTES;
          //echo "<li>"; 
          exit();
     }
     /*


     // # check self context (my-self) ? and reset CP root path
     $context = "";
     if ($isSelf) {
          // self project context
          $context = "self"; 
          $path_ZP_cpRoot .= '/../..';
          $path_apiphp     = 'static/api';
     } else {
          // consumer project context
          $context = "consumer"; 
          // all should be fine now, or ?
          if (!$isConsumer) {
               // am I in linked mode?
               $context = "consumer-linked"; 
               $path_ZP_cpRoot .= '/../../../svelte-zeeltephp';
               $path_apiphp     = 'static/api';
          }
          // -- other env ?
     }


          */
} 


?>